### ISSUE TITLE
Question: what should actually happen?

### ISSUE THREAD

**Issue by hanetzer** [mike-petersen/g15daemon#1]
Since you've forked this, I assume you've used it? Have you ran into an issue where the normal keyboard part stops working? I'm actually working on a on a libudev/uhid rewrite plus support for more devices

**Comment by mike-petersen** [comment]
I tried it but unfortunately had the same problems. I tried to find a way around it, but did not find a solution.

I would be interested on your rewrite.

Regards
Mike

**Comment by hanetzer** [comment]
What devices do you currently own? Did this ever work for you? Do you think I could dump some info for me?

**Comment by mike-petersen** [comment]
I have a logitech g510. Yes it worked, but not for very long. After max. a few minutes i could not use the keyboard anymore and needed to restart.

Of cause i can dump some info for you. What do you need?

**Comment by hanetzer** [comment]
https://github.com/GSeriesDev/gseries-tools , check CONTRIBUTING.md for the data I'd like to have.

**Comment by mike-petersen** [comment]
I made a pull request for the first informations. Will add the rest later:
https://github.com/GSeriesDev/gseries-tools/pull/1

**Comment by hanetzer** [comment]
Merged. I'd it's all the same to you, we can move this conversation to the gseries-tools repo

**Comment by mike-petersen** [comment]
sure
